# Generated by Django 4.2.11 on 2024-04-30 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lawsuits_dates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Responsible_for_lawsuits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Lawsuits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lawsuit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.lawsuits_dates')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.responsible_for_lawsuits')),
            ],
        ),
    ]
