# Generated by Django 4.2.11 on 2024-05-04 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_lawsuits_info_lawsuits_dates_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawsuits_dates',
            name='date',
            field=models.DateField(),
        ),
    ]
